let students = [
  {
    name: "Kehinde Omomobi",
    relationship: "Maried",
    number: "+233263559969",
    location: "Ghana",
    picture: "./images/kenny.jpg",
  },
  {
    name: "Stella Solomon",
    relationship: "Maried",
    number: "09061519745",
    location: "Lagos",
    picture: "./images/stella.jpg",
  },

  {
    name: "Ethang",
    relationship: "######",
    number: "XXXXXXXXX",
    location: ".Lagos",
    picture: "./images/ethan.jpg",
  },
  {
    name: "Ayoni Ogundele",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/ayoni.jpg",
  },
  {
    name: "Hakim",
    relationship: "######",
    number: "+226 55 75 52 56",
    location: "Bokina Faso",
    picture: "./images/hakim.jpg",
  },
  {
    name: "Annabel",
    relationship: "Single",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/hanna.jpg",
  },
  {
    name: "Emmanuel Emugan",
    relationship: "Single",
    number: "XXXXXXXXXXX",
    location: "Nigeria",
    picture: "./images/emugan.jpg",
  },

  {
    name: "Ayo",
    relationship: "Maried",
    number: "",
    location: "Lagos",
    picture: "./images/ayo.jpg",
  },
  {
    name: "Dearest Bright C Eze",
    relationship: "Single",
    number: "XXXXXXXXX",
    location: "Nigeria",
    picture: "./images/donatus.jpg",
  },
  {
    name: "Destiny Clark",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/destiny.jpg",
  },

  {
    name: "Gideon Philonis",
    relationship: "Single",
    number: "XXXXXXXXXXX",
    location: "Nigeria",
    picture: "./images/gideon.jpg",
  },
  {
    name: "Dorathy Mathias Mfoniso",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/dorathy.jpg",
  },
  {
    name: "Emmanuel Kumson",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Ghana",
    picture: "./images/kumson.jpg",
  },
  {
    name: " Gideon Akpotaire",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
    picture: "./images/gideon.jpg",
  },
  {
    name: "Orji Nneka Rosemary",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/ineka.jpg",
  },
  {
    name: "Samson Ocran",
    relationship: "Single",
    number: "+2348149835668",
    location: "Lagos",
    picture: "./images/sammy.jpg",
  },
  {
    name: "Gift Anthony",
    relationship: "######",
    number: "XXXXXXXXXXX",
    location: "Lagos",
    picture: "./images/gift.jpg",
  },
  {
    name: "Thomas Ogbor",
    relationship: "Single",
    number: "+XXXXXXXXXXX",
    location: "Lagos",
    picture: "./images/thomas.jpg",
  },

  {
    name: "David Imo",
    relationship: "Single",
    number: "+234 806 331 3939",
    location: "Lagos",
    picture: "./images/imo.jpg",
  },
  {
    name: "Oladimeji Paul Roland",
    relationship: "######",
    number: "08070995900",
    location: "Nigeria",
    picture: "./images/jimoh.jpg",
  },

  {
    name: "Omolayo Esther",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
  },
  {
    name: "Ajiboye Ibukunoluwa",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Lagos",
  },
  {
    name: "Esther Nse",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
  },
  {
    name: "Joke Ibk Lasore",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Anita Mj",
    relationship: "######",
    number: "08062892146",
    location: "Lagos",
  },
  {
    name: "Balogun Dare",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Temmy Ogundele",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Lagos",
  },
];
