let students = [
  {
    name: "Kehinde Omomobi",
    nickName: "Kenny",
    occupation: "*********",
    hobbies: "************",
    relationship: "Maried",
    number: "+233263559969",
    location: "Ghana",
    picture: "./images/kenny.jpg",
  },
  {
    name: "Stella Solomon",
    nickName: "***********",
    occupation: "**********",
    hobbies: "**********",
    relationship: "Maried",
    number: "+2349061519745",
    location: "Lagos",
    picture: "./images/stella.jpg",
  },

  {
    name: "Inieke Ethang",
    nickName: "Agba-killer",
    occupation: "********",
    hobbies: "********",
    relationship: "Complecated",
    number: "+234 810 018 0162",
    location: ".Lagos",
    picture: "./images/ethan.jpg",
  },
  {
    name: "Ayoni Ogundele",
    nickName: "Ayoni",
    occupation: "********",
    hobbies: "********",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/ayoni.jpg",
  },
  {
    name: "Hakim",
    nickName: "Cause trouble",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "+226 55 75 52 56",
    location: "Bokina Faso",
    picture: "./images/hakim.jpg",
  },
  {
    name: "Hannah Nnabue",
    nickName: "Annabel",
    occupation: "********",
    hobbies: "********",
    relationship: "Single",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/hanna.jpg",
  },
  {
    name: "Emmanuel Emurghan",
    nickName: "Junior Salvation",
    occupation: "Footballer",
    hobbies: "Football,",
    relationship: "Single",
    number: "XXXXXXXXXXX",
    location: "Nigeria",
    picture: "./images/emugan.jpg",
  },

  {
    name: "Ayo",
    nickName: "######",
    occupation: "******",
    hobbies: "********",
    relationship: "Maried",
    number: "+234 813 117 7796",
    location: "Lagos",
    picture: "./images/ayo.jpg",
  },
  {
    name: "Donatus Eze",
    nickName: "Dearest442",
    occupation: "Phone & Computer Repairs $ Sales",
    hobbies: "Musics & playing lead Guitar",
    relationship: "Maried",
    number: "+234 813 390 0757",
    location: "Bayelsa ",
    picture: "./images/donatus.jpg",
  },
  {
    name: "Destiny Clark",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/destiny.jpg",
  },

  {
    name: "Gideon Philonis",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "Single",
    number: "XXXXXXXXXXX",
    location: "Nigeria",
    picture: "./images/gideon.jpg",
  },
  {
    name: "Dorathy Mathias Mfoniso",
    nickName: "Dorathy",
    occupation: "*********",
    hobbies: "*************",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/dorathy.jpg",
  },
  {
    name: "Emmanuel Kumson",
    nickName: "Kumson",
    occupation: "*********",
    hobbies: "************",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Ghana",
    picture: "./images/kumson.jpg",
  },
  {
    name: "Ajiboye ibukun",
    nickName: "Highbeekay",
    occupation: "Entrepreneur",
    hobbies: " Dancing 💃, Singing 🎵 & Sleeping ",
    relationship: "Maried",
    number: "+234 813 407 4720",
    location: "Ibadan ",
    picture: "./images/ibukun.jpg",
  },
  {
    name: " Gideon Akpotaire",
    nickName: "######",
    occupation: "********",
    hobbies: "***********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
    picture: "./images/gideon.jpg",
  },
  {
    name: "Orji Nneka Rosemary",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/ineka.jpg",
  },
  {
    name: "Samson Ocran",
    nickName: "Sammini",
    occupation: "Network & System Engr(Software Developer)",
    hobbies: "Music, Video Games & Snooker",
    relationship: "Single",
    number: "+2349049043494",
    location: "Lagos",
    picture: "./images/sammy.jpg",
  },
  {
    name: "Gift Anthony",
    nickName: "######",
    occupation: "********",
    hobbies: "***********",
    relationship: "######",
    number: "XXXXXXXXXXX",
    location: "Lagos",
    picture: "./images/gift.jpg",
  },
  {
    name: "Thomas Ogbor",
    relationship: "Single",
    nickName: "Tommylynxx",
    occupation: "Traveler ",
    hobbies: "Football,long tennis,T.T,Snooker & Music",
    number: "+234 814 700 6217",
    location: "Cross River",
    picture: "./images/tommy.jpg",
  },
  {
    name: "Sherifat Salawudeen",
    relationship: "Maried",
    nickName: "Sheri",
    occupation: "Teaching,Vendor (wares , honey and perfumes)",
    hobbies: "Dancing, meeting people & teaching",
    number: "+234 904 164 5721",
    location: "Lagos",
    picture: "./images/sherifat2.PNG",
  },
  {
    name: "Stephen ishola",
    nickName: "Lilyo63 ",
    occupation: "Retail, Sales Administrator",
    hobbies: "********",
    relationship: "Maried",
    number: "+234 703 025 8480",
    location: "Lagos",
    picture: "./images/lilyo2.PNG",
  },
  {
    name: " Elegushi Adebisi",
    nickName: "Bisi",
    occupation: "Fashion Designer & Entrepreneur",
    hobbies: " Dancing, meeting people & Swimming",
    relationship: "Single",
    number: "+2348069781215",
    location: "Nigeria",
    picture: "./images/olabisi.png",
  },
  {
    name: "David Imo",
    nickName: "######",
    occupation: "Student",
    hobbies: "********",
    relationship: "Single",
    number: "+234 806 331 3939",
    location: "Lagos",
    picture: "./images/imo.jpg",
  },
  {
    name: "Oladimeji Paul Roland",
    nickName: "######",
    occupation: "Chef",
    hobbies: "Cooking, Football Games,",
    relationship: "######",
    number: "+2348070995900",
    location: "Nigeria",
    picture: "./images/jimoh.jpg",
  },

  {
    name: "Omolayo Esther",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
  },
  {
    name: "Moses Eromosele",
    nickName: "MO",
    occupation: "Welder",
    hobbies: "Football & Games",
    relationship: "Single",
    number: "+2349075684831",
    location: "Lagos",
  },
  {
    name: "Joke Ibk Lasore",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Anita Mj",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "08062892146",
    location: "Lagos",
  },
  {
    name: "Balogun Dare",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Precious Irika",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Osinachi",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Kazeem",
    nickName: "Dargrin",
    occupation: "Driver",
    hobbies: "driving & football",
    relationship: "Complecated",
    number: "+234 707 087 7329",
    location: "Nigeria",
  },
  {
    name: "Mary Inyaka",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Chijioke",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
 {
    name: "Seun",
    nickName: "Half Nose",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
   {
    name: "Bukky",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Augusta",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Zoe",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "John Bull",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Sahidi",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Amarachi",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Lin-on-God",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
];
