let students = [
  {
    name: "Kehinde Omomobi",
    nickName: "Kenny",
    occupation: "*********",
    hobbies: "************",
    relationship: "Maried",
    number: "+233263559969",
    location: "Ghana",
    picture: "./images/kenny.jpg",
  },
  {
    name: "Stella Solomon",
    nickName: "***********",
    occupation: "**********",
    hobbies: "**********",
    relationship: "Maried",
    number: "09061519745",
    location: "Lagos",
    picture: "./images/stella.jpg",
  },

  {
    name: "Inieke Ethang",
    nickName: "Agba-killer",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: ".Lagos",
    picture: "./images/ethan.jpg",
  },
  {
    name: "Ayoni Ogundele",
    nickName: "Ayoni",
    occupation: "********",
    hobbies: "********",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/ayoni.jpg",
  },
  {
    name: "Hakim",
    nickName: "Cause trouble",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "+226 55 75 52 56",
    location: "Bokina Faso",
    picture: "./images/hakim.jpg",
  },
  {
    name: "Hanna Nnabwe",
    nickName: "Annabel",
    occupation: "********",
    hobbies: "********",
    relationship: "Single",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/hanna.jpg",
  },
  {
    name: "Emmanuel Emugan",
    nickName: "Junior Salvation",
    occupation: "Footballer",
    hobbies: "Football,",
    relationship: "Single",
    number: "XXXXXXXXXXX",
    location: "Nigeria",
    picture: "./images/emugan.jpg",
  },

  {
    name: "Ayo",
    nickName: "######",
    occupation: "******",
    hobbies: "********",
    relationship: "Maried",
    number: "XXXXXXXX",
    location: "Lagos",
    picture: "./images/ayo.jpg",
  },
  {
    name: "Donatus Eze",
    nickName: "Dearest442",
    occupation: "Phone & Computer Repairs $ Sales",
    hobbies: "Musics & playing lead Guitar",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Bayelsa ",
    picture: "./images/donatus.jpg",
  },
  {
    name: "Destiny Clark",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/destiny.jpg",
  },

  {
    name: "Gideon Philonis",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "Single",
    number: "XXXXXXXXXXX",
    location: "Nigeria",
    picture: "./images/gideon.jpg",
  },
  {
    name: "Dorathy Mathias Mfoniso",
    nickName: "Dorathy",
    occupation: "*********",
    hobbies: "*************",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/dorathy.jpg",
  },
  {
    name: "Emmanuel Kumson",
    nickName: "Kumson",
    occupation: "*********",
    hobbies: "************",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Ghana",
    picture: "./images/kumson.jpg",
  },
  {
    name: "Ajiboye ibukun",
    nickName: "Highbeekay",
    occupation: "*********",
    hobbies: " Dancing 💃, Singing 🎵 & Sleeping ",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Ibadan ",
    picture: "./images/ibukun.jpg",
  },
  {
    name: " Gideon Akpotaire",
    nickName: "######",
    occupation: "********",
    hobbies: "***********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
    picture: "./images/gideon.jpg",
  },
  {
    name: "Orji Nneka Rosemary",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
    picture: "./images/ineka.jpg",
  },
  {
    name: "Samson Ocran",
    nickName: "Sammini",
    occupation: "Network & System Engr(Software Developer)",
    hobbies: "Music, Video Games & Snooker",
    relationship: "Single",
    number: "+2349049043494",
    location: "Lagos",
    picture: "./images/sammy.jpg",
  },
  {
    name: "Gift Anthony",
    nickName: "######",
    occupation: "********",
    hobbies: "***********",
    relationship: "######",
    number: "XXXXXXXXXXX",
    location: "Lagos",
    picture: "./images/gift.jpg",
  },
  {
    name: "Thomas Ogbor",
    relationship: "Single",
    nickName: "Tommylynxx",
    occupation: "Traveler ",
    hobbies: "Football,long tennis,T.T,Snooker & Music",
    number: "+XXXXXXXXXXX",
    location: "Cross River",
    picture: "./images/tommy.jpg",
  },
  {
    name: "Stephen ishola",
    nickName: "Lilyo63 ",
    occupation: "Retail, Sales Administrator",
    hobbies: "********",
    relationship: "######",
    number: "Maried",
    location: "Lagos",
    picture: "./images/lilyo2.PNG",
  },

  {
    name: "David Imo",
    nickName: "######",
    occupation: "Student",
    hobbies: "********",
    relationship: "Single",
    number: "+234 806 331 3939",
    location: "Lagos",
    picture: "./images/imo.jpg",
  },
  {
    name: "Oladimeji Paul Roland",
    nickName: "######",
    occupation: "Chef",
    hobbies: "Football, Music & Travelling",
    relationship: "######",
    number: "08070995900",
    location: "Nigeria",
    picture: "./images/jimoh.jpg",
  },

  {
    name: "Omolayo Esther",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
  },
  {
    name: "Ajiboye Ibukunoluwa",
    nickName: "######",
    occupation: "*********",
    hobbies: "**************",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
  },
  {
    name: "Esther Nse",
    nickName: "######",
    occupation: "*********",
    hobbies: "********",
    relationship: "Maried",
    number: "XXXXXXXXX",
    location: "Lagos",
  },
  {
    name: "Joke Ibk Lasore",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
  {
    name: "Anita Mj",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "08062892146",
    location: "Lagos",
  },
  {
    name: "Balogun Dare",
    nickName: "######",
    occupation: "********",
    hobbies: "********",
    relationship: "######",
    number: "XXXXXXXXX",
    location: "Nigeria",
  },
];
